import Link from 'next/link';
import { ArrowRight, Bot, Braces, Check, Cloud, Code2, Database, Layers3, LockKeyhole, Palette, Rocket, ShieldCheck, Sparkles, Workflow } from 'lucide-react';

const services = [
  { icon: Code2, number: '01', title: 'Software Development', text: 'Purpose-built platforms and enterprise applications engineered around your operating model.', tags: ['Web apps', 'APIs', 'Custom software'] },
  { icon: Layers3, number: '02', title: 'Web & Mobile', text: 'Fast, accessible product experiences that make complex workflows feel simple everywhere.', tags: ['React', 'Next.js', 'Mobile'] },
  { icon: Bot, number: '03', title: 'AI & Automation', text: 'Useful intelligence for your teams, from LLM-powered products to dependable internal tools.', tags: ['LLM apps', 'AI APIs', 'Automation'] },
  { icon: Cloud, number: '04', title: 'Cloud & DevOps', text: 'Cloud foundations that are observable, resilient, and ready to grow with the business.', tags: ['Architecture', 'CI/CD', 'Infrastructure'] },
  { icon: Palette, number: '05', title: 'UI/UX & Product Design', text: 'Clear product thinking and expressive interfaces that earn trust at every interaction.', tags: ['UX strategy', 'Design systems', 'Prototyping'] },
  { icon: Workflow, number: '06', title: 'Digital Transformation', text: 'Modernize the systems and processes that are holding your next chapter back.', tags: ['Modernization', 'Automation', 'Advisory'] },
];
const technologies = ['React', 'Next.js', 'TypeScript', 'Node.js', 'Python', 'MongoDB', 'PostgreSQL', 'AWS', 'Docker', 'OpenAI', 'LangChain', 'GitHub'];
const industries = ['Startups', 'FinTech', 'E-commerce', 'Education', 'Healthcare', 'SaaS', 'Enterprise', 'Digital platforms'];
const process = [['01', 'Discover', 'Understand the opportunity, users, and constraints.'], ['02', 'Strategize', 'Shape the product direction and technical architecture.'], ['03', 'Design', 'Turn the strategy into an intuitive product experience.'], ['04', 'Develop', 'Build clean, secure, production-ready software.'], ['05', 'Launch & scale', 'Deploy, learn, optimize, and keep moving forward.']];

export const metadata = { title: 'VAM|Tech | Building technology that moves business forward', description: 'VAM|Tech builds scalable digital products and intelligent software solutions through engineering, design, AI, and cloud expertise.' };

export default function HomePage() {
  return <div className="site-home">
    <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Product-minded technology partners</div><h1>Building technology that moves <em>business forward.</em></h1><p className="hero-lede">VAM|Tech helps businesses transform ideas into scalable digital products through software engineering, AI, cloud, and modern technology solutions.</p><div className="hero-actions"><Link href="/contact" className="button button-dark">Start a project <ArrowRight size={17} /></Link><Link href="#services" className="button button-link">Explore services <ArrowRight size={17} /></Link></div><div className="hero-proof"><span><Check size={15} /> Senior-led delivery</span><span><Check size={15} /> Built for what is next</span></div></div><div className="hero-visual" aria-label="Abstract connected technology systems visual"><div className="visual-grid" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="visual-core"><span>VAM</span><strong>TECH</strong></div><div className="signal-card signal-top"><span className="signal-icon"><Sparkles size={16} /></span><span><small>INTELLIGENCE</small><b>Ideas → impact</b></span></div><div className="signal-card signal-bottom"><span className="signal-icon signal-green"><Rocket size={16} /></span><span><small>DELIVERY</small><b>Built to scale</b></span></div><span className="visual-node node-a" /><span className="visual-node node-b" /><span className="visual-node node-c" /></div></section>
    <section className="stats-band"><div className="container stats-grid"><div><strong>10<span>+</span></strong><small>Projects shipped</small></div><div><strong>5<span>+</span></strong><small>Technology domains</small></div><div><strong>100<span>%</span></strong><small>Client focus</small></div><div><strong>24<span>/7</span></strong><small>Curiosity in motion</small></div></div></section>
    <section id="services" className="section container"><div className="section-heading"><div><span className="kicker">What we do</span><h2>Technology with a point of view.</h2></div><p>We bring product thinking, engineering discipline, and a human understanding of your business to every engagement.</p></div><div className="service-grid">{services.map(({ icon: Icon, ...service }) => <article className="service-card" key={service.number}><div className="card-top"><span className="service-number">{service.number}</span><Icon size={24} strokeWidth={1.5} /></div><h3>{service.title}</h3><p>{service.text}</p><div className="tag-row">{service.tags.map(tag => <span key={tag}>{tag}</span>)}</div><Link href="/services" className="card-link">Learn more <ArrowRight size={16} /></Link></article>)}</div></section>
    <section className="dark-section"><div className="container dark-layout"><div><span className="kicker kicker-light">Why VAM|Tech</span><h2>Good technology should make ambition feel <em>practical.</em></h2><p className="dark-lede">The best solutions are not the loudest ones. They are the ones that make a team faster, a customer happier, and a business ready for its next move.</p><Link href="/about" className="button button-light">Meet the team <ArrowRight size={17} /></Link></div><div className="principles"><div><ShieldCheck size={22} /><span><b>Secure by design</b><small>Trust is built into the foundation.</small></span></div><div><Braces size={22} /><span><b>Clean engineering</b><small>Simple systems are easier to grow.</small></span></div><div><Database size={22} /><span><b>Scalable architecture</b><small>Ready for the user you have not met yet.</small></span></div><div><LockKeyhole size={22} /><span><b>Clear communication</b><small>No black boxes. No surprise handoffs.</small></span></div></div></div></section>
    <section className="section container stack-section"><div className="section-heading"><div><span className="kicker">Our toolkit</span><h2>Built with the right tools for the job.</h2></div><p>Technology is a means, not a badge. We choose the stack that keeps your product fast, flexible, and maintainable.</p></div><div className="tech-cloud">{technologies.map((tech, index) => <span className={index % 5 === 0 ? 'tech-pill tech-accent' : 'tech-pill'} key={tech}>{tech}</span>)}</div></section>
    <section className="industry-section"><div className="container"><div className="section-heading"><div><span className="kicker">Where we help</span><h2>From first release to next horizon.</h2></div><Link href="/solutions" className="button button-outline">Explore solutions <ArrowRight size={17} /></Link></div><div className="industry-grid">{industries.map((industry, index) => <Link href="/solutions" className="industry-item" key={industry}><span>0{index + 1}</span><strong>{industry}</strong><ArrowRight size={17} /></Link>)}</div></div></section>
    <section className="section container process-section"><div className="section-heading"><div><span className="kicker">How we work</span><h2>A clear path from idea to impact.</h2></div><p>Every engagement is shaped around momentum, shared context, and measurable progress.</p></div><div className="process-grid">{process.map(([number, title, text]) => <div className="process-step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
    <section className="project-feature container"><div className="project-art"><div className="project-window"><div className="window-bar"><i /><i /><i /></div><div className="chart-lines"><span /><span /><span /><span /></div><div className="chart-axis"><b>Growth</b><b>Clarity</b><b>Speed</b></div></div></div><div className="project-copy"><span className="kicker">Featured project / 01</span><h2>Making complexity feel beautifully simple.</h2><p>A flexible operations platform for teams that had outgrown disconnected tools. Designed to bring signal, structure, and momentum into one shared workspace.</p><div className="tag-row"><span>Product strategy</span><span>Next.js</span><span>Node.js</span></div><Link href="/projects" className="card-link">View case studies <ArrowRight size={16} /></Link></div></section>
    <section className="about-strip"><div className="container about-layout"><div><span className="kicker">A little about us</span><h2>We build what we wish existed.</h2></div><div><p>VAM|Tech is a technology-driven company focused on building reliable software, intelligent digital products, and scalable solutions. We combine engineering, design, and emerging technologies to help businesses turn ideas into real-world products.</p><Link href="/about" className="card-link">More about VAM|Tech <ArrowRight size={16} /></Link></div></div></section>
    <section className="cta-section"><div className="container cta-inner"><div><span className="kicker kicker-light">Ready when you are</span><h2>Have an idea? Let&apos;s build it <em>together.</em></h2></div><Link href="/contact" className="button button-light">Start a conversation <ArrowRight size={17} /></Link></div></section>
  </div>;
}
